#
# Baking!
#

# ------------------------------------------------------------------------------
# Input files
# ------------------------------------------------------------------------------
STATIC_LIB	:= libsequest-kernels.a

CU_DEPS		:= kernels.h mass.h operator.h
CUFILES		:=
CUFILES_sm_11	:=

C_DEPS		:= utils.h
CFILES		:= utils.c
CCFILES		:=

INCLUDES	:=


# ------------------------------------------------------------------------------
# Rules and targets
# ------------------------------------------------------------------------------
SRCDIR		:= .
DISTROOT	:= ../dist

include ../common.mk

